### ISSUE TITLE
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

### ISSUE THREAD

**Issue by nnleaf** [chrisbergeron/pihole_influx#4]
I'm running PiHole on a Debian VM and after running for a few days, pihole-influx service is shown as failed and gives this error

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

Reloading the daemon seems to resolve the issue until it pops up again. Any ideas?

**Comment by chrisbergeron** [comment]
Solution here: https://dev.to/brisbanewebdeveloper/amend-journal-has-been-rotated-since-unit-was-started-on-x1-extreme-gen-2-x1e2-5eme
